### ISSUE TITLE
Not working appropriately.

### ISSUE THREAD

**Issue by Jessen21** [MADH95/JSONLoaderPlugin#3] opened 2021-11-23 21:20 UTC
Not sure why its happening, was working fine last night, now its not.

[Info   :JSONCardLoader] Loaded JSONCardLoader!
[Info   :JSONCardLoader] Loading from Garter Snake.json...
[Error  : Unity Log] MissingMethodException: void APIPlugin.NewCard.Add(string,System.Collections.Generic.List`1<DiskCardGame.CardMetaCategory>,DiskCardGame.CardComplexity,CardTemple,string,int,int,string,bool,int,int,int,System.Collections.Generic.List`1<DiskCardGame.GemType>,DiskCardGame.SpecialStatIcon,System.Collections.Generic.List`1<DiskCardGame.Tribe>,System.Collections.Generic.List`1<DiskCardGame.Trait>,System.Collections.Generic.List`1<DiskCardGame.SpecialTriggeredAbility>,System.Collections.Generic.List`1<DiskCardGame.Ability>,System.Collections.Generic.List`1<APIPlugin.AbilityIdentifier>,DiskCardGame.EvolveParams,string,DiskCardGame.TailParams,DiskCardGame.IceCubeParams,bool,bool,System.Collections.Generic.List`1<DiskCardGame.CardAppearanceBehaviour/Appearance>,UnityEngine.Texture2D,UnityEngine.Texture2D,UnityEngine.Texture,UnityEngine.Texture2D,UnityEngine.GameObject,System.Collections.Generic.List`1<UnityEngine.Texture>)
Stack trace:
JLPlugin.Plugin.Awake () (at <93256ed9070f40f3bbda463b370fef9a>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Sirenix.Serialization.UnitySerializationInitializer:Initialize()
Sirenix.Serialization.UnitySerializationInitializer:InitializeRuntime()

**Comment by MADH95** [comment] 2021-11-23 21:37
Did you update to API 1.12?

**Comment by Jessen21** [comment] 2021-11-23 21:51
I've been trying that quite a bit, back and forth.

**Comment by Jessen21** [comment] 2021-11-23 22:04
i'm going to try and get it loaded up on a computer that hasn't had it yet and see if I can work it out.

**Comment by Jessen21** [comment] 2021-11-23 22:26
ok, so definitely API related, for sure, but the exact reasoning the error was happening even with 1.11? not sure. I have redone my mods just to see what was working with what and should have it stable for now, but theres definitely a situation that may need to be looked into eventually.

**Comment by MADH95** [comment] 2021-11-23 23:27
V1.6.1 works only with API v1.11. The update for API v1.12 isn't released yet. The error you're getting is caused by a missmatch between jsonloader version and the API version. I'm closing this issue, as this isn't the place for tech support, you should put your queries in the #Tech-Support channel of the modding discord, you can find a link in the README if you not in it already.

**Closed by MADH95** 2021-11-23 23:27 UTC
